Repository jenkins-x/terraform-azurerm-jx, pull requests merged in 2020-09, with the labels that each got.

#15 feat: Re-enabling CI pipeline
  .gitignore
  jenkins-x.yml
  local.tf
  main.tf
  modules/backup/local.tf
  modules/backup/main.tf
  modules/backup/outputs.tf
  modules/backup/variables.tf
  modules/cluster/main.tf
  modules/cluster/outputs.tf
  modules/cluster/variables.tf
  modules/dns/local.tf
  modules/dns/main.tf
  modules/dns/outputs.tf
  modules/dns/variables.tf
  modules/jx-requirements.yml.tpl
  modules/registry/main.tf
  modules/registry/variables.tf
  modules/vault/keyvault.tf
  modules/vault/local.tf
  modules/vault/main.tf
  modules/vault/outputs.tf
  modules/vault/storage.tf
  modules/vault/variables.tf
  modules/vnet/main.tf
  modules/vnet/outputs.tf
  modules/vnet/variables.tf
  outputs.tf
  test/file_operations.go
  variables.tf
Labels: approved, lgtm, ok-to-test, size/L

#19 fix: Sanitize storage account name + removed deprecated dns_enabled v…
  README.md
  local.tf
  main.tf
  modules/backup/main.tf
  modules/backup/variables.tf
  modules/vault/local.tf
  modules/vault/variables.tf
Labels: size/M

#25 fix: Prevent domain name output from dns module if external dns is no…
  modules/dns/outputs.tf
Labels: approved, lgtm, size/XS

#27 feat: enable specification of node_resource_group for AKS cluster resources
  README.md
  local.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/M

#26 fix: Enabled domain discovery when external_dns is disabled
  README.md
  jenkins-x.yml
  main.tf
  modules/jx-requirements.yml.tpl
  outputs.tf
Labels: approved, lgtm, ok-to-test, size/S

#31 fix: Fixed path to jx-requirements file
  main.tf
Labels: approved, lgtm, size/XS

#32 feat: added in native key vault secret storage
  config.tf
  local.tf
  main.tf
  modules/jx-requirements.yml.tpl
  modules/keyvault/auth.tf
  modules/keyvault/keyvault.tf
  modules/keyvault/local.tf
  modules/keyvault/outputs.tf
  modules/keyvault/variables.tf
  modules/vault/keyvault.tf
  modules/vault/outputs.tf
  modules/vault/storage.tf
  modules/vault/variables.tf
  outputs.tf
  variables.tf
Labels: approved, lgtm, size/L

#33 Add output cluster_node_resource_group
  README.md
  outputs.tf
Labels: approved, ok-to-test, size/XS

#35 feat: Add in jx-git-operator chart
  README.md
  config.tf
  main.tf
  modules/cluster/charts.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/M

#34 feat: aadpod_identity
  .gitignore
  README.md
  config.tf
  local.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/outputs.tf
  modules/cluster/variables.tf
  modules/vault/auth.tf
  modules/vault/keyvault.tf
  modules/vault/outputs.tf
  modules/vault/variables.tf
  modules/workloadidentity/local.tf
  modules/workloadidentity/main.tf
  modules/workloadidentity/variables.tf
  outputs.tf
  test/cluster_operations.go
  test/environment.go
  test/storage_accounts.go
  test/terraform_edns_cluster_test.go
  test/terraform_jx_cluster_with_container_registry_test.go
  test/terraform_workload_identity_test.go
  test/tokens.go
  test_commands/cmd/verify_key_vault/main.go
  test_commands/go.mod
  variables.tf
Labels: approved, lgtm, size/L
