Repository jenkins-x/terraform-azurerm-jx, pull requests merged in 2020-11, with the labels that each got.

#42 feat: consolidated secret storage down to single module to simplify the configuration
  .gitignore
  Makefile
  config.tf
  local.tf
  main.tf
  modules/backup/main.tf
  modules/cluster/main.tf
  modules/keyvault/auth.tf
  modules/keyvault/keyvault.tf
  modules/keyvault/local.tf
  modules/keyvault/outputs.tf
  modules/keyvault/variables.tf
  modules/secretstorage/common.tf
  modules/secretstorage/local.tf
  modules/secretstorage/non-native.tf
  modules/secretstorage/outputs.tf
  modules/secretstorage/variables.tf
  modules/vault/auth.tf
  modules/vault/local.tf
  modules/vault/main.tf
  modules/vault/outputs.tf
  modules/vault/storage.tf
  outputs.tf
  test/terraform_jx_cluster_test.go
  test/terraform_workload_identity_test.go
Labels: size/L

#43 feat: Added in log analytics integration to cluster
  README.md
  main.tf
  modules/cluster/logging.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: size/M

#46 fix: added lifecycle ignore (back) to metadata.labels on secret-infra ns.
  modules/cluster/main.tf
Labels: approved, size/XS

#47 feat: made container registry creation mandatory to provide better out of the box experience
  local.tf
  main.tf
  modules/cluster/main.tf
  modules/registry/main.tf
  modules/registry/variables.tf
  test/terraform_jx_cluster_test.go
  test/terraform_jx_cluster_with_container_registry_test.go
  variables.tf
Labels: size/L

#48 chore: refactored how External DNS and Azure DNS are supported via this module
  README.md
  config.tf
  main.tf
  modules/dns/main.tf
  modules/dns/outputs.tf
  modules/dns/variables.tf
  modules/jx-requirements.yml.tpl
  outputs.tf
  test/terraform_edns_cluster_test.go
  variables.tf
Labels: approved, lgtm, size/M

#49 fix: set sensitive for the bot token
  modules/cluster/charts.tf
Labels: approved, lgtm, ok-to-test, size/XS

#51 feat: added in jx kuberhealthy chart. minor refactor to separate k8s cluster from jx pre-req artefacts
  local.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/outputs.tf
  modules/cluster/variables.tf
  modules/jx/charts.tf
  modules/jx/variables.tf
  modules/workloadidentity/local.tf
  modules/workloadidentity/variables.tf
  test/terraform_cluster_backup_test.go
  test/terraform_edns_cluster_test.go
  test/terraform_jx_cluster_test.go
  test/terraform_workload_identity_test.go
Labels: size/M

#52 chore: removed native secret storage variable for now as more work is required on jx side to support this and just confusing users currently
  README.md
  local.tf
  main.tf
  variables.tf
Labels: size/S
